export interface Drill {
  id: number;
  name: string;
  slug: string;
  category: "standard" | "waterbag";
  villain: string;
  tagline: string;
  whatItIs: string;
  whyWeDoit: string;
  howToRunIt: string;
  coachingCues: string;
  videoUrl: string;
  videoUrl2?: string;
  thumbnailUrl: string;
  storyAngle: string;
}

// YouTube thumbnail helper — hqdefault gives the best quality that's always available
function yt(videoId: string): string {
  return `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
}

export const drills: Drill[] = [
  {
    id: 1,
    name: "Piggyback Drill",
    slug: "piggyback-drill",
    category: "standard",
    villain: "Getting stuck back. Falling forward.",
    tagline: "Helps you feel your launch position",
    whatItIs: "A partner gets on your back while you execute your forward stride, forcing your body to find its strongest, most balanced hitting position automatically.",
    whyWeDoit: "We want you to feel your launch position. Once you feel it, you start to notice when you're not getting to it. This also helps you clean up your load and might show you that you don't need to shift backwards in your load.",
    howToRunIt: "Have a partner get on your back piggyback-style. Start in your normal stance. Take your stride forward. Feel where your weight naturally lands — that's your real launch position.",
    coachingCues: "Counter rotate your shoulders as you move forward to help you feel like you're staying back as you're moving forward.",
    videoUrl: "https://www.youtube.com/watch?v=XZErWca31uM",
    videoUrl2: "https://youtu.be/e2HPp_EMYls",
    thumbnailUrl: yt("XZErWca31uM"),
    storyAngle: "The hitter who had the 'perfect' stride — and why it was secretly destroying his power.",
  },
  {
    id: 2,
    name: "Wiffle Ball Bat Drill",
    slug: "wiffle-ball-bat-drill",
    category: "standard",
    villain: "The 'push it the other way' cue",
    tagline: "Teaches you how to actually pull the ball — in the air",
    whatItIs: "Rapid-fire hitting with a wiffle ball bat and slow-arc tosses. The batter abandons their stance and swings with pure instinct, trying to hit every ball as a pull-side home run.",
    whyWeDoit: "Most hitters are taught to 'push the barrel the other way,' which creates weak ground balls. This drill teaches the correct pulling motion by turning the brain off entirely.",
    howToRunIt: "Grab a wiffle bat and bucket of wiffle balls. Tosser throws slow, high arcs. Batter swings continuously without resetting feet — pure momentum, no mechanics.",
    coachingCues: "Forget you play baseball. Pretend you're Ken Griffey Jr. Hit pull-side homers only. Don't stop to reset. Let your feet be free.",
    videoUrl: "https://www.youtube.com/watch?v=NC9QB1HTmnc",
    thumbnailUrl: yt("NC9QB1HTmnc"),
    storyAngle: "The hitter who was taught to 'push it the other way' — and why that cue turned him into a ground ball machine.",
  },
  {
    id: 3,
    name: "Happy Gilmore Drill",
    slug: "happy-gilmore-drill",
    category: "standard",
    villain: "Mindless, mechanical repetition",
    tagline: "Restores explosive intent and natural athleticism",
    whatItIs: "The batter performs a hard, aggressive shuffle forward as the pitch is delivered, swinging with maximum power as if they only have one shot.",
    whyWeDoit: "Over-coaching drains the athleticism out of hitters. This drill breaks players out of robotic habits by treating every swing like an Olympic event.",
    howToRunIt: "Normal stance. As the pitch comes, initiate a hard shuffle forward. Swing for maximum distance. Keep reps low (5-6 max) to maintain full intent.",
    coachingCues: "Pretend you only have one pitch. Pretend this is an Olympic event. Shuffle hard. Hit this ball as far as you possibly can.",
    videoUrl: "https://www.youtube.com/watch?v=ZE4uxo0QoUQ",
    thumbnailUrl: yt("ZE4uxo0QoUQ"),
    storyAngle: "The over-coached hitter who forgot what it felt like to just swing.",
  },
  {
    id: 4,
    name: "The Ali Drill",
    slug: "ali-drill",
    category: "standard",
    villain: "The myth that power comes from going backward",
    tagline: "Teaches hitters to catch the ball out front and flush it",
    whatItIs: "Front toss drill focused on hitting the ball out in front of the plate with maximum force, eliminating the backward load myth.",
    whyWeDoit: "Power doesn't come from going backward. It comes from catching the ball out front. This drill teaches hitters to get to their strong spots without overthinking.",
    howToRunIt: "Standard front toss setup. Focus entirely on making contact out front. Allow the brain to be quieter — just get to your strong spots.",
    coachingCues: "Allow your brain to be a little quieter. Focus on getting to your strong spots. Power comes from catching the ball out front, not from a big load.",
    videoUrl: "https://www.youtube.com/watch?v=AlAWSztSbL8",
    thumbnailUrl: yt("AlAWSztSbL8"),
    storyAngle: "The hitter who kept loading harder trying to hit for more power — and kept getting weaker.",
  },
  {
    id: 5,
    name: "Self-Toss Fungo",
    slug: "self-toss-fungo",
    category: "standard",
    villain: "Starting too easy and pushing the barrel — or jumping straight to full speed before you're loose",
    tagline: "A great way to start your day and get loose the right way",
    whatItIs: "You toss the ball up and hit it yourself. Start by hitting ground balls to different parts of the field — third, short, second, first — then build your way up to line drives as you loosen up. Walk into your swing instead of standing still to find rhythm and pace.",
    whyWeDoit: "Most hitters start their session either too easy (pushing the barrel) or too hard (ripping full speed before they're ready). This drill teaches you to control your effort level, start low, and build up. It also cleans up a lot of mechanical issues — but we won't list them here because we don't want you to overanalyze.",
    howToRunIt: "Toss the ball up and out in front of you — not jamming yourself — so you can get loose. Start hitting ground balls to each part of the field. Think like an infielder: you want a nice, comfortable ground ball to start, not a rocket. Once you've hit ground balls in both directions, move to line drives. Walk into the swing to find your rhythm.",
    coachingCues: "Change your target, not your swing. If you're rolling over to the left side, switch your target to the right side and think 'middle.' Don't get internal and wonder what's wrong — your swing is fine, just change your external target.",
    videoUrl: "https://www.youtube.com/watch?v=B-D7MQzGlnk",
    thumbnailUrl: yt("B-D7MQzGlnk"),
    storyAngle: "The hitter who only worked hard when a coach was watching.",
  },
  {
    id: 6,
    name: "Top Hand Drill",
    slug: "top-hand-drill",
    category: "standard",
    villain: "Passive top hand that kills bat speed",
    tagline: "Activates the top hand for explosive barrel acceleration",
    whatItIs: "Hitting drill using only the top hand to force it to become an active, powerful participant in the swing rather than just going along for the ride.",
    whyWeDoit: "Most hitters have a dominant bottom hand and a passive top hand. Activating the top hand dramatically increases bat speed and barrel control.",
    howToRunIt: "Remove the bottom hand from the bat. Hit with top hand only. Focus on driving the barrel through the zone aggressively.",
    coachingCues: "Your top hand should be driving, not following. Feel it accelerate the barrel. That's the hand that creates bat speed.",
    videoUrl: "https://www.youtube.com/watch?v=8wK78H_4YNc",
    thumbnailUrl: yt("8wK78H_4YNc"),
    storyAngle: "The hitter with great mechanics and no bat speed — because one hand was asleep.",
  },
  {
    id: 7,
    name: "The Recoil Drill",
    slug: "recoil-drill",
    category: "standard",
    villain: "The 'start your load earlier' fix for being late",
    tagline: "Fixes being late without changing your timing",
    whatItIs: "A drill that teaches hitters to recoil and redirect their energy forward explosively, fixing lateness without the counterproductive 'start earlier' cue.",
    whyWeDoit: "Telling a late hitter to 'start sooner' makes them mechanical and even slower. The Recoil Drill teaches the body to redirect energy explosively — the real fix for being late.",
    howToRunIt: "Start in your stance. Initiate a small recoil backward, then explode forward into your swing. The recoil creates elastic energy that makes you faster, not slower.",
    coachingCues: "Don't start earlier. Recoil and explode. The energy you store going back is what makes you fast going forward.",
    videoUrl: "https://www.youtube.com/watch?v=CKQ0lI8gKXg",
    thumbnailUrl: yt("CKQ0lI8gKXg"),
    storyAngle: "The hitter who kept being told to 'start sooner' — and kept getting later.",
  },
  {
    id: 8,
    name: "The Step Back Drill",
    slug: "step-back-drill",
    category: "standard",
    villain: "Lunging and losing posture at contact",
    tagline: "Teaches balance and posture through the entire swing",
    whatItIs: "The hitter steps back with the front foot after contact, training the body to maintain posture and balance through the entire swing plane.",
    whyWeDoit: "Hitters who lunge lose their posture and their power. Stepping back forces the body to stay tall and balanced through contact.",
    howToRunIt: "Take your normal swing. After contact, step back with your front foot. Feel how your posture must stay tall to execute this correctly.",
    coachingCues: "Stay tall. Don't lunge. Your posture through contact determines your power at contact.",
    videoUrl: "https://www.youtube.com/watch?v=B-akFoWwmpk",
    thumbnailUrl: yt("B-akFoWwmpk"),
    storyAngle: "The hitter who looked great in slow motion but fell apart at full speed.",
  },
  {
    id: 9,
    name: "Rapid Fire Side Toss",
    slug: "rapid-fire-side-toss",
    category: "standard",
    villain: "Overthinking between swings",
    tagline: "Forces the brain to shut off and let the body take over",
    whatItIs: "Continuous rapid-fire side toss where the hitter must swing immediately after each toss with no time to think between reps.",
    whyWeDoit: "When hitters have too much time between swings, they overthink. Rapid fire removes the thinking window and forces pure athletic response.",
    howToRunIt: "Tosser throws immediately after each swing. Hitter must be ready. No pausing. No resetting. Pure continuous movement.",
    coachingCues: "No thinking. Just react. The ball is coming whether you're ready or not. Trust your body.",
    videoUrl: "https://www.youtube.com/watch?v=imPA0mOn8F4",
    thumbnailUrl: yt("imPA0mOn8F4"),
    storyAngle: "The hitter who was great in slow practice and terrible in fast games.",
  },
  {
    id: 10,
    name: "The Tracer Drill",
    slug: "tracer-drill",
    category: "standard",
    villain: "Poor barrel path and casting",
    tagline: "Trains the barrel to stay in the zone longer",
    whatItIs: "A drill that traces the correct barrel path through the hitting zone, training muscle memory for a longer, more consistent contact window.",
    whyWeDoit: "Hitters who cast the barrel have a tiny contact window. The Tracer Drill builds the muscle memory for a barrel path that stays in the zone longer.",
    howToRunIt: "Slowly trace the barrel through the hitting zone, feeling the correct path. Then execute full swings maintaining that path.",
    coachingCues: "Feel the barrel staying in the zone. Don't cast. Stay connected. Longer barrel path means more consistent contact.",
    videoUrl: "https://www.youtube.com/watch?v=sUErvr0qLtw",
    thumbnailUrl: yt("sUErvr0qLtw"),
    storyAngle: "The hitter with a beautiful swing who couldn't make consistent contact.",
  },
  {
    id: 11,
    name: "The McGwire Drill",
    slug: "mcgwire-drill",
    category: "standard",
    villain: "Weak, disconnected lower half",
    tagline: "Builds explosive rotational power from the ground up",
    whatItIs: "A power-focused drill inspired by Mark McGwire's legendary lower half engagement, training the hips and legs to drive the swing.",
    whyWeDoit: "Most hitters swing with their arms. Power hitters swing with their legs and hips. This drill teaches the lower half to lead the swing.",
    howToRunIt: "Exaggerate hip rotation and lower half drive. Feel the ground. Push off hard. Let the upper body follow the lower body's lead.",
    coachingCues: "The power starts at your feet. Push the ground away. Your hips lead. Your hands follow.",
    videoUrl: "https://www.youtube.com/watch?v=hJs3F8OR9Jo",
    thumbnailUrl: yt("hJs3F8OR9Jo"),
    storyAngle: "The hitter who had great arm strength and no power — because his legs were spectators.",
  },
  {
    id: 12,
    name: "Bat Drop Drill",
    slug: "bat-drop-drill",
    category: "standard",
    villain: "Casting and early extension",
    tagline: "Fixes the most common power leak in youth hitters",
    whatItIs: "The hitter intentionally drops the bat head to an extreme angle, then fires through contact, training the correct inside-out path.",
    whyWeDoit: "Casting and early extension are the most common power leaks. The exaggerated bat drop trains the body to keep the barrel inside the ball.",
    howToRunIt: "Start with an exaggerated bat drop — barrel pointing almost straight down. Then fire through the zone. Feel the difference in barrel path.",
    coachingCues: "Drop it. Then fire. Feel the barrel staying inside. That's the path that creates power.",
    videoUrl: "https://www.youtube.com/watch?v=_s9aHueL65I",
    thumbnailUrl: yt("_s9aHueL65I"),
    storyAngle: "The hitter who kept rolling over on inside pitches no matter how much he practiced.",
  },
  {
    id: 13,
    name: "Turn the Corner Drill",
    slug: "turn-the-corner-drill",
    category: "standard",
    villain: "Spinning out and losing direction",
    tagline: "Teaches the hips to turn through the ball, not around it",
    whatItIs: "A drill that trains the hips to turn through the hitting zone rather than spinning out, maintaining direction and power through contact.",
    whyWeDoit: "Hitters who spin out lose power and direction. Turning the corner keeps the hips driving through the ball instead of past it.",
    howToRunIt: "Focus on driving the back hip through the zone. Imagine turning a corner — not spinning in a circle. Feel the difference in direction.",
    coachingCues: "Turn through it, not around it. Drive the hip. Stay on the ball. Don't spin.",
    videoUrl: "https://www.youtube.com/watch?v=w-gDrqNYeHU",
    thumbnailUrl: yt("w-gDrqNYeHU"),
    storyAngle: "The hitter who had great hip rotation and no power — because he was spinning, not driving.",
  },
  {
    id: 14,
    name: "Bottom Hand Drill",
    slug: "bottom-hand-drill",
    category: "standard",
    villain: "Dominant bottom hand that pulls the barrel off plane",
    tagline: "Balances the hands for a cleaner, more consistent swing",
    whatItIs: "Hitting with only the bottom hand to isolate and train its role in the swing — guiding the barrel rather than dominating it.",
    whyWeDoit: "An overdominant bottom hand pulls the barrel off plane and creates inconsistent contact. Isolating it teaches the correct role of each hand.",
    howToRunIt: "Remove the top hand. Hit with bottom hand only. Focus on guiding the barrel through the zone rather than pulling it.",
    coachingCues: "Guide, don't pull. Your bottom hand sets the path. Your top hand provides the power. They have different jobs.",
    videoUrl: "https://www.youtube.com/watch?v=R1qgjfjHOUE",
    thumbnailUrl: yt("R1qgjfjHOUE"),
    storyAngle: "The hitter whose dominant hand was sabotaging his swing without either of them knowing it.",
  },
  {
    id: 15,
    name: "Step Back Drill Variation",
    slug: "step-back-drill-variation",
    category: "standard",
    villain: "Inconsistent posture across different pitch locations",
    tagline: "Builds posture consistency on all pitch locations",
    whatItIs: "A variation of the Step Back Drill applied to different pitch locations, training the body to maintain posture regardless of where the ball is.",
    whyWeDoit: "Hitters often maintain posture on middle pitches but collapse on low ones or lunge on high ones. This variation trains posture consistency everywhere.",
    howToRunIt: "Apply the step-back technique to inside, outside, high, and low pitches. Feel how posture must adapt but never collapse.",
    coachingCues: "Same posture. Different location. Your spine angle doesn't change based on where the pitch is.",
    videoUrl: "https://www.youtube.com/watch?v=Ku9TrLL3pRk",
    thumbnailUrl: yt("Ku9TrLL3pRk"),
    storyAngle: "The hitter who looked great on middle pitches and fell apart everywhere else.",
  },
  {
    id: 16,
    name: "Start at Release Drill",
    slug: "start-at-release-drill",
    category: "standard",
    villain: "Premature loading and timing disruption",
    tagline: "Syncs the load to the pitcher's release point",
    whatItIs: "The hitter begins their load precisely when the pitcher releases the ball, training perfect timing synchronization.",
    whyWeDoit: "Hitters who load too early or too late are always fighting timing. Starting at release syncs the body's movement to the actual pitch, not an imagined one.",
    howToRunIt: "Watch the pitcher's hand. The moment the ball leaves the hand, begin your load. Not before. Not after. At release.",
    coachingCues: "Watch the hand. Start at release. Your body moves when the ball moves. Not before.",
    videoUrl: "https://www.youtube.com/watch?v=XJ2KphcvSw4",
    thumbnailUrl: yt("XJ2KphcvSw4"),
    storyAngle: "The hitter who was always early or always late — never on time.",
  },
  {
    id: 17,
    name: "Silent Swings",
    slug: "silent-swings",
    category: "standard",
    villain: "Verbal cues that interrupt natural movement",
    tagline: "Trains the body to move without the brain narrating",
    whatItIs: "Swings taken in complete silence — no coaching cues, no internal dialogue, no swing thoughts. Pure athletic movement.",
    whyWeDoit: "The brain's verbal narration interferes with the body's natural movement patterns. Silent swings train the athlete to move without the brain getting in the way.",
    howToRunIt: "Take swings with zero internal dialogue. No swing thoughts. No cues. Just see the ball and swing. If a thought enters, let it pass.",
    coachingCues: "No thoughts. No cues. Just see it and hit it. Your body already knows how to do this.",
    videoUrl: "https://www.youtube.com/watch?v=z5GCHdtezA0",
    thumbnailUrl: yt("z5GCHdtezA0"),
    storyAngle: "The hitter who couldn't take a single swing without narrating it to himself.",
  },
  {
    id: 18,
    name: "Chuckit Drill",
    slug: "chuckit-drill",
    category: "standard",
    villain: "Stiff, mechanical arm path",
    tagline: "Frees up the arms and creates natural bat speed",
    whatItIs: "The hitter 'chucks' the bat through the zone with a loose, free arm swing, training natural arm path and bat speed.",
    whyWeDoit: "Over-coached hitters develop stiff, mechanical arm paths. The Chuckit Drill restores the natural, loose arm swing that creates real bat speed.",
    howToRunIt: "Think about throwing the bat through the zone. Loose arms. Free swing. Chuck it. Feel the natural acceleration.",
    coachingCues: "Throw it. Loose arms. Free it up. That looseness is where your bat speed lives.",
    videoUrl: "https://youtu.be/ZcmiKqGekc4",
    thumbnailUrl: yt("ZcmiKqGekc4"),
    storyAngle: "The hitter with perfect mechanics and no bat speed — because he was too tight.",
  },
  {
    id: 19,
    name: "Split Grip Hockey Stick Drill",
    slug: "split-grip-hockey-stick-drill",
    category: "standard",
    villain: "Disconnected hands and poor sequencing",
    tagline: "Trains hand separation and proper swing sequencing",
    whatItIs: "Using a hockey stick with a split grip, the hitter trains the correct hand separation and sequencing that creates a powerful, connected swing.",
    whyWeDoit: "When the hands work together incorrectly, the swing falls apart. The split grip forces the hands to work in the correct sequence.",
    howToRunIt: "Hold a hockey stick with hands split apart. Execute swings focusing on the correct sequencing of each hand through the zone.",
    coachingCues: "Feel the sequence. Bottom hand first. Top hand through. They have different jobs and different timing.",
    videoUrl: "https://youtu.be/pzBwNFNnm9M",
    thumbnailUrl: yt("pzBwNFNnm9M"),
    storyAngle: "The hitter whose hands looked connected but were secretly fighting each other.",
  },
  {
    id: 20,
    name: "Hook 'em Drill",
    slug: "hook-em-drill",
    category: "standard",
    villain: "Casting and early barrel extension",
    tagline: "Keeps the barrel inside the ball for maximum power",
    whatItIs: "A drill that trains the 'hook' motion of the barrel staying inside the ball before extending through contact.",
    whyWeDoit: "Casting the barrel early is one of the most common power leaks. The Hook 'em Drill trains the barrel to stay inside before extending.",
    howToRunIt: "Focus on the barrel hooking inside the ball before extension. Feel the difference between casting and staying inside.",
    coachingCues: "Hook it inside first. Then extend. Inside-out is the path. Casting is the enemy.",
    videoUrl: "https://youtu.be/T-JZvL4r9fc",
    thumbnailUrl: yt("T-JZvL4r9fc"),
    storyAngle: "The hitter who kept being told to 'stay inside' but never understood what that meant.",
  },
  {
    id: 21,
    name: "The Knob to Knee Drill",
    slug: "knob-to-knee-drill",
    category: "standard",
    villain: "High hands and a long swing path",
    tagline: "Creates the shortest, most direct path to the ball",
    whatItIs: "The hitter drives the knob of the bat directly toward the front knee, training the shortest possible path to contact.",
    whyWeDoit: "Long swing paths create late contact and weak hits. Driving the knob to the knee creates the shortest path and the most direct barrel delivery.",
    howToRunIt: "Focus on driving the knob toward the front knee as you initiate the swing. Feel how this shortens the path and speeds up the barrel.",
    coachingCues: "Knob to knee. Short path. Direct delivery. The shortest distance between two points is a straight line.",
    videoUrl: "https://youtu.be/lWblISE-TsM",
    thumbnailUrl: yt("lWblISE-TsM"),
    storyAngle: "The hitter who was always a little late — because his path to the ball was twice as long as it needed to be.",
  },
  {
    id: 22,
    name: "Ready at Release",
    slug: "ready-at-release",
    category: "standard",
    villain: "Being caught unprepared at the moment of pitch release",
    tagline: "Trains the body to be fully loaded and ready at the right moment",
    whatItIs: "A timing drill that trains the hitter to be in their fully loaded, ready position precisely when the pitcher releases the ball.",
    whyWeDoit: "Hitters who aren't ready at release are always reacting instead of attacking. Being ready at release means attacking the pitch, not chasing it.",
    howToRunIt: "Watch the pitcher's release point. Your goal: be fully loaded and ready the moment the ball leaves the hand. Attack from there.",
    coachingCues: "Ready at release. Not before. Not after. At release. Attack from your ready position.",
    videoUrl: "https://youtu.be/6gdISAqOkUo",
    thumbnailUrl: yt("6gdISAqOkUo"),
    storyAngle: "The hitter who was always reacting to pitches instead of attacking them.",
  },
  {
    id: 23,
    name: "Side-to-Side Water Bag Rip",
    slug: "side-to-side-water-bag-rip",
    category: "waterbag",
    villain: "One-dimensional rotational patterns",
    tagline: "Builds rotational power in both directions",
    whatItIs: "Using a water bag, the athlete rips from side to side, building rotational strength and power in both directions.",
    whyWeDoit: "Baseball hitters develop one-sided rotational patterns. Side-to-side work builds balanced rotational power and prevents the imbalances that lead to injury.",
    howToRunIt: "Hold the water bag. Rip it from right to left, then left to right. Focus on explosive hip rotation driving each movement.",
    coachingCues: "Hips first. Arms follow. Explosive rotation. Feel the water shift — that's your power transferring.",
    videoUrl: "https://www.youtube.com/watch?v=J41XBcz_zUk",
    thumbnailUrl: yt("J41XBcz_zUk"),
    storyAngle: "The hitter who was strong on one side and had no idea the other side was holding him back.",
  },
  {
    id: 24,
    name: "Water Bag Rotational Flow",
    slug: "water-bag-rotational-flow-drill",
    category: "waterbag",
    villain: "Choppy, disconnected rotational mechanics",
    tagline: "Creates smooth, connected rotational flow",
    whatItIs: "A water bag drill focused on creating smooth, continuous rotational flow rather than choppy, disconnected movement patterns.",
    whyWeDoit: "Choppy rotation wastes energy and reduces power. Rotational flow creates a continuous chain of energy transfer from the ground through the bat.",
    howToRunIt: "Hold the water bag. Focus on smooth, continuous rotation — no stopping, no jerking. Let the water's momentum guide the flow.",
    coachingCues: "Smooth. Connected. Let the water flow. Your rotation should feel like one continuous movement, not three separate ones.",
    videoUrl: "https://www.youtube.com/watch?v=LU3xXjK7sQc",
    thumbnailUrl: yt("LU3xXjK7sQc"),
    storyAngle: "The hitter who worked hard on rotation and still had no power — because his mechanics were choppy.",
  },
  {
    id: 25,
    name: "Water Bag Rotational Activation",
    slug: "water-bag-rotational-activation-drill",
    category: "waterbag",
    villain: "Dormant rotational muscles that don't fire in games",
    tagline: "Wakes up the rotational muscles before they're needed",
    whatItIs: "A water bag activation drill designed to fire up the rotational muscles before practice or games, ensuring they're ready to perform.",
    whyWeDoit: "Muscles that aren't activated don't perform. This drill wakes up the specific rotational muscles needed for hitting before they're called upon in competition.",
    howToRunIt: "Use the water bag to perform controlled rotational movements, progressively increasing intensity. Focus on feeling the muscles activate and engage.",
    coachingCues: "Feel it wake up. Start slow. Build intensity. By the time you're done, your rotation should feel alive.",
    videoUrl: "https://www.youtube.com/watch?v=w62NShmFpBI",
    thumbnailUrl: yt("w62NShmFpBI"),
    storyAngle: "The hitter who warmed up his arms but never warmed up the muscles that actually create his power.",
  },
  {
    id: 26,
    name: "Tall Shuffle and Rip",
    slug: "tall-shuffle-and-rip",
    category: "waterbag",
    villain: "Collapsing posture during dynamic movement",
    tagline: "Builds power while maintaining elite posture",
    whatItIs: "The athlete shuffles laterally while maintaining tall posture, then rips the water bag explosively, training power generation from a strong, upright position.",
    whyWeDoit: "Most power drills allow posture to collapse. Tall Shuffle and Rip trains the athlete to generate explosive power while staying tall — the position that transfers to the swing.",
    howToRunIt: "Shuffle laterally, staying tall. At the end of the shuffle, rip the water bag explosively. Maintain your height throughout.",
    coachingCues: "Stay tall. Don't collapse. Power from a tall position. The shuffle creates momentum. The rip converts it.",
    videoUrl: "https://www.youtube.com/watch?v=-Qa-_4DPTag",
    thumbnailUrl: yt("-Qa-_4DPTag"),
    storyAngle: "The hitter who was powerful in isolation but lost it all when he had to move.",
  },
  {
    id: 27,
    name: "Dynamic Movement Rotational Swing",
    slug: "dynamic-movement-rotational-swing",
    category: "waterbag",
    villain: "Static practice that doesn't transfer to dynamic game situations",
    tagline: "Bridges the gap between practice mechanics and game athleticism",
    whatItIs: "A water bag drill combining dynamic movement with rotational swinging, training the body to generate power while in motion.",
    whyWeDoit: "Hitters who only practice from a static position struggle when they have to move. This drill trains power generation from dynamic positions.",
    howToRunIt: "Start in motion. Add the rotational swing. Feel how dynamic movement can enhance rather than disrupt power generation.",
    coachingCues: "Move and swing. Don't stop to hit. The movement feeds the swing. Let it.",
    videoUrl: "https://www.youtube.com/watch?v=0ToA6FaPYtM",
    thumbnailUrl: yt("0ToA6FaPYtM"),
    storyAngle: "The hitter who looked great in the cage and fell apart when the pitcher made him move.",
  },
  {
    id: 28,
    name: "Waterbag Toss",
    slug: "waterbag-toss",
    category: "waterbag",
    villain: "Arm-dominant power patterns",
    tagline: "Forces the whole body to generate power, not just the arms",
    whatItIs: "The athlete tosses the water bag explosively, training whole-body power generation with the arms as the final link in the chain.",
    whyWeDoit: "Arm-dominant hitters have a ceiling on their power. The water bag toss is too heavy to throw with just arms — it forces the entire kinetic chain to engage.",
    howToRunIt: "Hold the water bag. Toss it explosively. If you're using only your arms, it won't go far. Let your legs and hips drive it.",
    coachingCues: "Legs. Hips. Arms. In that order. If your arms are working first, you're doing it wrong.",
    videoUrl: "https://www.youtube.com/watch?v=XC97SsMtEGM",
    thumbnailUrl: yt("XC97SsMtEGM"),
    storyAngle: "The hitter who had strong arms and no power — because his arms were doing all the work.",
  },
  {
    id: 29,
    name: "Happy Gilmore Waterbag Toss",
    slug: "happy-gilmore-waterbag-toss",
    category: "waterbag",
    villain: "Timid, mechanical power generation",
    tagline: "Unlocks explosive, uninhibited power from dynamic movement",
    whatItIs: "The Happy Gilmore shuffle combined with a water bag toss, training explosive power generation from dynamic forward movement.",
    whyWeDoit: "Combining the Happy Gilmore shuffle with the water bag toss creates the most explosive power training possible — dynamic movement feeding into maximum force production.",
    howToRunIt: "Shuffle forward aggressively. At the peak of your momentum, toss the water bag explosively. Let the shuffle feed the toss.",
    coachingCues: "Shuffle hard. Toss harder. The momentum from the shuffle becomes the power in the toss. Don't fight it — use it.",
    videoUrl: "https://www.youtube.com/watch?v=v5319qHDmsY",
    thumbnailUrl: yt("v5319qHDmsY"),
    storyAngle: "The hitter who trained power in isolation but couldn't access it when he had to move.",
  },
  {
    id: 30,
    name: "The Nine Pocket Drill",
    slug: "nine-pocket-drill",
    category: "waterbag",
    villain: "Inconsistency across different pitch locations",
    tagline: "Builds power and consistency to all nine zones",
    whatItIs: "A water bag drill targeting all nine zones of the strike zone, training the body to generate power consistently regardless of pitch location.",
    whyWeDoit: "Most hitters have one or two zones where they're powerful and seven where they're weak. The Nine Pocket Drill builds consistent power everywhere.",
    howToRunIt: "Work through all nine zones — high/middle/low, inside/middle/outside. Each zone requires a slightly different body position. Train them all.",
    coachingCues: "Nine zones. Nine different body positions. Same power. Consistency is the goal.",
    videoUrl: "https://www.youtube.com/watch?v=fK8KANl5-TQ",
    thumbnailUrl: yt("fK8KANl5-TQ"),
    storyAngle: "The hitter who was a monster on middle-middle and helpless everywhere else.",
  },
  {
    id: 31,
    name: "Lasso Drill",
    slug: "lasso-drill",
    category: "waterbag",
    villain: "Tight, restricted arm path",
    tagline: "Frees up the arms for maximum bat speed",
    whatItIs: "Using the water bag in a lasso motion, the athlete trains a free, loose arm path that creates maximum bat speed.",
    whyWeDoit: "Tight arm paths restrict bat speed. The lasso motion trains the arms to be loose and free — the physical state that creates the most bat speed.",
    howToRunIt: "Swing the water bag in a lasso motion. Feel the looseness. Feel the speed. That looseness is what you want in your swing.",
    coachingCues: "Loose. Free. Fast. Tight arms are slow arms. Let the lasso teach you what loose feels like.",
    videoUrl: "https://www.youtube.com/watch?v=g23SZr8fmzE",
    thumbnailUrl: yt("g23SZr8fmzE"),
    storyAngle: "The hitter who trained hard every day and never got faster — because he was training tightness.",
  },
  {
    id: 32,
    name: "Fogel Water Bag Drill",
    slug: "fogel-water-bag-drill",
    category: "waterbag",
    villain: "Disconnected upper and lower body rotation",
    tagline: "Creates a unified, connected rotational chain",
    whatItIs: "A specialized water bag drill that trains the connection between upper and lower body rotation, creating a unified rotational chain.",
    whyWeDoit: "When the upper and lower body rotate independently, power leaks out of the kinetic chain. The Fogel Drill trains them to work as one connected unit.",
    howToRunIt: "Focus on feeling the lower body initiate and the upper body follow as one connected movement. The water bag provides feedback on whether you're connected.",
    coachingCues: "Lower body leads. Upper body follows. Connected. One movement. If you feel disconnected, you are disconnected.",
    videoUrl: "https://www.youtube.com/watch?v=z3ujjB5FCaw",
    thumbnailUrl: yt("z3ujjB5FCaw"),
    storyAngle: "The hitter who had a powerful lower half and a powerful upper half — that never talked to each other.",
  },
];

export const standardDrills = drills.filter(d => d.category === "standard");
export const waterbagDrills = drills.filter(d => d.category === "waterbag");
