export interface Drill {
  id: number;
  name: string;
  slug: string;
  category: "standard" | "waterbag";
  villain: string;
  tagline: string;
  whatItIs: string;
  whyWeDoit: string;
  howToRunIt: string;
  coachingCues: string;
  videoUrl: string;
  videoUrl2?: string;
  thumbnailUrl: string;
  storyAngle?: string;
}

// YouTube thumbnail helper — hqdefault gives the best quality that's always available
function yt(videoId: string): string {
  return `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`;
}

export const drills: Drill[] = [
  {
    id: 1,
    name: "Piggyback Drill",
    slug: "drill",
    category: "standard",
    villain: "You're not loading your back hip. You're losing power.",
    tagline: "Feel your back hip load and explode through the ball.",
    whatItIs: "This drill is all about feeling that back hip work. You'll get into your stance, then push off your back leg like you're trying to jump. You're essentially 'piggybacking' your weight onto that back hip.",
    whyWeDoit: "We do this drill to teach you how to properly load your back hip. This is where your power comes from, and if you don't load it, you're leaving a lot of velocity and exit speed on the table. It helps you connect your lower half to your swing.",
    howToRunIt: "Start in your normal batting stance. Focus on your back hip. Push off your back foot, feeling your weight shift onto that back hip. Hold that loaded position for a second, then fire through your swing. Repeat this feeling for every rep. Make sure you're really feeling that push.",
    coachingCues: "Load that hip. Push off. Feel the power. Explode through.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 2,
    name: "Wiffle Ball Bat Drill",
    slug: "drill",
    category: "standard",
    villain: "You swing too hard, losing control. You miss the sweet spot often.",
    tagline: "Find your rhythm, control your swing, hit the sweet spot.",
    whatItIs: "Grab a wiffle ball and a bat. You're going to take some easy swings, focusing on making solid contact. It's all about feeling the barrel hit the ball.",
    whyWeDoit: "This drill helps you slow down and really feel your swing. It teaches you to control the bat head and consistently hit the ball in the right spot, which means more solid contact in games.",
    howToRunIt: "Set up a tee or have a friend soft toss wiffle balls to you. Take 10-15 swings, focusing on hitting the ball squarely. Don't try to crush it; just make good contact. Repeat this a few times, really feeling the barrel.",
    coachingCues: "Easy swing. Feel the barrel. Stay through it. Square it up.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 3,
    name: "Happy Gilmore Drill",
    slug: "drill",
    category: "standard",
    villain: "You're not generating enough power. Your swing feels weak and disconnected.",
    tagline: "Unleash your inner Happy Gilmore for explosive power.",
    whatItIs: "This drill is all about getting your body to work together to create maximum power. You'll take a running start, just like Happy Gilmore, and then explode into your swing. It's about feeling that full body rotation and transfer of energy.",
    whyWeDoit: "We do this drill to teach you how to use your entire body, not just your arms, to generate power. It helps you understand the sequence of a powerful swing and how to really drive through the ball. You'll feel a significant increase in bat speed and exit velocity.",
    howToRunIt: "Start about 10-15 feet behind home plate. Take a few steps, building momentum, then plant your front foot and swing hard. Focus on rotating your hips and shoulders together. Really try to feel like you're throwing the bat at the ball. Repeat this 5-7 times, then take a normal swing.",
    coachingCues: "Run through it. Explode to the ball. Drive your hips. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 4,
    name: "The Ali Drill",
    slug: "drill",
    category: "standard",
    villain: "You're slow off the mound. Your footwork is sloppy and costing you power.",
    tagline: "Quick feet, powerful throws. Feel like a pro.",
    whatItIs: "This drill is all about getting your feet moving fast and efficiently. You'll be working on quick steps and good balance, just like a boxer. It's about being light on your feet and ready to explode.",
    whyWeDoit: "We do this drill to build explosive power from the ground up. If your feet aren't quick and coordinated, you're leaving a lot of velocity on the table. This helps you get into a strong throwing position every time.",
    howToRunIt: "Start in your ready position. Take quick, choppy steps forward, then back, then side to side. Stay on the balls of your feet, light and agile. Focus on staying balanced and controlled throughout the movement. Do this for 30 seconds, then rest for 30 seconds. Repeat 3-5 times.",
    coachingCues: "Quick feet. Stay light. Explode. Be an athlete.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 5,
    name: "Self-Toss Fungo",
    slug: "drill",
    category: "standard",
    villain: "You're missing easy ground balls. Your hands aren't quick enough to react.",
    tagline: "Improve your fielding reactions and hand-eye coordination.",
    whatItIs: "This drill is all about getting your hands ready for game-time plays. You'll toss the ball up yourself, then field it like a pro. It's a simple way to get a ton of reps in.",
    whyWeDoit: "We do this drill to build quick hands and soft hands. It helps you get comfortable with different hops and makes fielding ground balls second nature. You'll be ready for anything hit your way.",
    howToRunIt: "Start by standing in a good athletic position. Toss the ball a few feet in front of you, then react and field it cleanly. Focus on using your glove hand and getting your body in front of the ball. Repeat this process, varying your tosses to simulate different game situations.",
    coachingCues: "Quick hands. Soft hands. Get in front. See the hop.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 6,
    name: "Top Hand Drill",
    slug: "drill",
    category: "standard",
    villain: "Casting the barrel. Losing power and bat speed.",
    tagline: "Feel your top hand drive the barrel.",
    whatItIs: "This drill helps you focus on using your top hand to control the bat. You'll keep your bottom hand loose, almost like it's just along for the ride. It's all about feeling that top hand push the barrel through the zone.",
    whyWeDoit: "Too many hitters cast the barrel, losing all their power. This drill fixes that. It teaches you to keep your hands inside the ball and drive through it, creating more bat speed and harder contact.",
    howToRunIt: "Grab your bat and get in your stance. Keep your bottom hand relaxed, almost barely holding the bat. Focus on pushing the bat head with your top hand directly to the ball. Make sure your top hand stays connected and drives through the contact point. Repeat for 10-15 swings, really feeling that top hand work.",
    coachingCues: "Top hand strong. Drive the barrel. Stay inside. Explode through.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 7,
    name: "The Recoil Drill",
    slug: "drill",
    category: "standard",
    villain: "This drill fixes hitters who don't use their lower half. It stops you from just swinging with your arms.",
    tagline: "Feel explosive power and drive through your swing.",
    whatItIs: "This drill teaches you to use your legs and hips for power. You'll learn to create a strong, athletic base before you swing. It's all about feeling that ground force.",
    whyWeDoit: "We do this drill to build explosive power from the ground up. It helps you transfer energy from your lower body into the ball. This means more bat speed and harder hits.",
    howToRunIt: "Start in your athletic stance, ready to hit. As you load, let your front foot lift slightly off the ground. Then, drive that front foot back down and push off hard. Focus on feeling a powerful recoil as you launch into your swing. Repeat this, really feeling the ground and driving through it.",
    coachingCues: "Stay tall. Explode forward. Feel the ground. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 8,
    name: "The Step Back Drill",
    slug: "drill",
    category: "standard",
    villain: "This drill fixes lazy feet and poor weight transfer. Stop leaving power on the table.",
    tagline: "Feel your power. Drive through the ball.",
    whatItIs: "You're going to take a small step back with your front foot before you stride. This helps you load up properly. Then, explode forward into your swing.",
    whyWeDoit: "Too many hitters don't use their lower half. This drill forces you to engage your legs and hips. It builds momentum and power, so you hit the ball harder.",
    howToRunIt: "Start in your normal batting stance. Take a small step back with your front foot, just a few inches. As you step back, load your weight onto your back leg. Then, stride forward and swing like normal. Focus on feeling that powerful drive from your back hip.",
    coachingCues: "Step back. Load up. Explode. Drive through it.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 9,
    name: "Rapid Fire Side Toss",
    slug: "drill",
    category: "standard",
    villain: "Slow bat speed. Poor hand-eye coordination.",
    tagline: "Explode your bat speed and sharpen your focus.",
    whatItIs: "You'll stand close to a screen, and a coach will toss balls quickly from the side. Your job is to hit every single one, fast and hard. It's all about quick reactions and powerful swings.",
    whyWeDoit: "This drill forces you to react instantly and swing with intent. It builds your hand-eye coordination and helps you develop that explosive bat speed you need to crush pitches.",
    howToRunIt: "Set up a screen about 5-10 feet in front of you. Have a coach or teammate toss balls rapidly from the side, aiming for your strike zone. Focus on making solid contact and driving the ball. Keep your head down and swing through the ball.",
    coachingCues: "Quick hands. See it, hit it. Explode. Stay through it.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 10,
    name: "The Tracer Drill",
    slug: "drill",
    category: "standard",
    villain: "Missing the ball. Not seeing the pitch clearly.",
    tagline: "See the ball better, hit it harder.",
    whatItIs: "You'll focus on tracking the baseball from the pitcher's hand all the way to your bat. It's all about training your eyes to follow the ball's path, like drawing a line in the air. This helps you make solid contact more consistently.",
    whyWeDoit: "This drill fixes your eyes from losing the ball mid-flight. When you track the ball better, you react quicker and hit with more power. It's about building that crucial hand-eye coordination.",
    howToRunIt: "Stand in your batting stance. Have a partner throw soft toss or front toss. Your only job is to call out 'tracer' as you see the ball leave their hand. Follow the ball with your eyes all the way to contact. Don't swing, just track and call it out.",
    coachingCues: "See the spin. Track it all the way. Eyes on the ball. Tracer!",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 11,
    name: "The McGwire Drill",
    slug: "drill",
    category: "standard",
    villain: "Are you swinging with just your arms? This drill fixes that weak, disconnected swing.",
    tagline: "Feel your whole body explode through the ball.",
    whatItIs: "This drill is all about getting your lower half involved in your swing. You'll focus on driving your hips and rotating powerfully, just like the big sluggers. It's about connecting your entire body to generate maximum bat speed.",
    whyWeDoit: "We do this drill to build a powerful, rotational swing. It teaches you to use your legs and core, not just your arms, to hit the ball harder and farther. This creates a more consistent and explosive swing.",
    howToRunIt: "Start with your feet wider than shoulder-width apart, holding the bat across your shoulders. Focus on initiating your swing with your hips, driving them forward and rotating them aggressively. Let your upper body follow naturally, feeling the power transfer from your lower half. Finish your swing balanced and strong, facing the pitcher. Repeat this motion, feeling the connection from the ground up.",
    coachingCues: "Hips first. Drive through the ball. Stay connected. Explode!",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 12,
    name: "Bat Drop Drill",
    slug: "drill",
    category: "standard",
    villain: "You're not finishing your swing. Your body stays stiff and you lose power.",
    tagline: "Finish your swing strong. Feel your power through the ball.",
    whatItIs: "You'll take your normal swing, but after contact, you'll let go of the bat. Just drop it right there. Then, focus on finishing your body rotation.",
    whyWeDoit: "This drill forces you to rotate fully through your swing. It helps you get all your power into the ball. You won't pull off the ball early.",
    howToRunIt: "Set up like you're going to hit a real pitch. Take your swing, driving through the ball. Immediately after contact, open your hands and let the bat fall. Keep your eyes on the ball and finish your rotation.",
    coachingCues: "Drop the bat. Finish your turn. Drive through it. Stay connected.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 13,
    name: "Turn the Corner Drill",
    slug: "drill",
    category: "standard",
    villain: "You're not getting around the bases fast enough. You're losing precious seconds at the turns.",
    tagline: "Explode around the bases, shave seconds off your time.",
    whatItIs: "This drill teaches you how to attack the bases. You'll learn to round the bags efficiently, keeping your momentum. It's all about speed and smart angles.",
    whyWeDoit: "Every second counts in baseball. A good turn can mean the difference between safe and out. This drill builds the muscle memory for aggressive, effective base running.",
    howToRunIt: "Start at first base. Sprint towards second, focusing on a wide arc. Touch the inside corner of the bag, then accelerate towards third. Repeat for all bases, aiming for smooth, powerful turns. Do this 5-7 times.",
    coachingCues: "Attack the bag. Wide arc. Explode off the corner. Stay low.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 14,
    name: "Bottom Hand Drill",
    slug: "drill",
    category: "standard",
    villain: "Swinging with weak hands or casting the bat. You're losing power and control.",
    tagline: "Feel your bottom hand drive the barrel through the ball.",
    whatItIs: "You're going to focus purely on your bottom hand. It's all about feeling that connection and driving through the ball. This drill helps you understand how much power comes from that lead hand.",
    whyWeDoit: "We do this drill to build strength and awareness in your bottom hand. It teaches you to control the barrel and generate real power, stopping those weak swings.",
    howToRunIt: "Grab your bat and take your normal stance. Focus all your attention on your bottom hand. As you swing, feel that hand driving the bat head directly to the ball. Make sure you're extending through contact, letting that bottom hand lead the way. Repeat this, really feeling the power transfer.",
    coachingCues: "Bottom hand strong. Drive the barrel. Extend through it. Feel the power.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 15,
    name: "Step Back Drill Variation",
    slug: "drill",
    category: "standard",
    villain: "You are rushing your swing. You are not getting your foot down in time.",
    tagline: "Feel your rhythm. Get your foot down. Crush the ball.",
    whatItIs: "This drill helps you slow down your load and get your foot down properly. You'll start with your back foot already lifted, then step back before moving forward into your swing. It's all about finding that perfect timing.",
    whyWeDoit: "We do this drill to fix timing issues. If your foot isn't down when you swing, you lose power and accuracy. This drill forces you to feel the rhythm and get into a strong hitting position.",
    howToRunIt: "Start with your back foot lifted, almost like you're ready to stride. Then, take a small step back with that foot. Immediately after, begin your normal stride and swing. Focus on feeling your body move in sequence. Repeat this for several swings, really feeling the timing.",
    coachingCues: "Foot down. Stay back. Feel the ground. Attack the ball.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 16,
    name: "Start at Release Drill",
    slug: "drill",
    category: "standard",
    villain: "You finish your throw too early. This drill fixes that.",
    tagline: "Feel your full extension and power through the ball.",
    whatItIs: "You'll start this drill at the very end of your throwing motion, right when the ball leaves your hand. Hold that position, feel it, and then work backward. It's all about understanding where you need to be at release.",
    whyWeDoit: "This drill helps you understand and feel the correct release point. It teaches your body to get into a powerful, extended position, which means more velocity and better accuracy on your throws.",
    howToRunIt: "Start with your arm fully extended, as if you just released the ball. Hold that position for a few seconds, feeling the stretch. Then, slowly reverse the motion, bringing your arm back to your ear. Repeat this slowly, focusing on that strong release point each time. Do this 10-15 times per arm.",
    coachingCues: "Finish strong. Extend, extend, extend. Feel the release. Get out front.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 17,
    name: "Silent Swings",
    slug: "drill",
    category: "standard",
    villain: "You're rushing your swing, losing power and control. This drill fixes that.",
    tagline: "Find your rhythm, feel the power, and slow the game down.",
    whatItIs: "This drill is all about finding your smooth, powerful swing without the pressure of hitting a ball. You'll focus on your mechanics and tempo, making sure every movement is intentional and strong. It's about building muscle memory for a perfect swing.",
    whyWeDoit: "We do this drill to eliminate rushed swings and help you connect with your body's natural power. When you slow down, you can feel each part of your swing, leading to better contact and more consistent hits. It's how you build a swing that works every time.",
    howToRunIt: "Grab your bat and find some space. Start with your normal stance, then take your swing in slow motion, focusing on every detail. Don't rush. Repeat this for 10-15 swings, really feeling the movement. Then, take a few normal-speed swings, trying to maintain that same smooth rhythm.",
    coachingCues: "Slow it down. Feel your feet. Stay connected. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 18,
    name: "Chuckit Drill",
    slug: "drill",
    category: "standard",
    villain: "You’re swinging too hard and losing control. This fixes your wild swings.",
    tagline: "Find your rhythm and control your swing.",
    whatItIs: "You're going to use a Chuckit to launch balls. Focus on a smooth, controlled swing. It's all about making solid contact, not hitting it a mile.",
    whyWeDoit: "This drill teaches you to stay balanced and make consistent contact. It helps you find your natural swing without overthinking. You'll hit more line drives and fewer pop-ups.",
    howToRunIt: "Grab a Chuckit and some tennis balls. Set up like you're at the plate. Toss the ball up with the Chuckit and hit it. Focus on staying through the ball and finishing your swing. Do 10-15 reps, then switch sides if you're ambidextrous.",
    coachingCues: "Smooth swing. Stay balanced. See the ball. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 19,
    name: "Split Grip Hockey Stick Drill",
    slug: "drill",
    category: "standard",
    villain: "Are you losing control of your bat? This drill fixes weak top hand and poor barrel control.",
    tagline: "Feel your top hand dominate the barrel.",
    whatItIs: "You're going to grab your bat with a split grip, like you're holding a hockey stick. Your top hand will be up by the knob, and your bottom hand will be further down the barrel. This helps you isolate and strengthen your top hand's role in controlling the bat.",
    whyWeDoit: "We do this drill to make sure your top hand is strong and active. A strong top hand means better barrel control, more consistent contact, and driving the ball with authority. It's all about getting that barrel where it needs to be.",
    howToRunIt: "Set up in your normal batting stance. Take dry swings, focusing on feeling your top hand guide the barrel through the zone. Make sure your top hand is doing the work, not just along for the ride. Do 10-15 swings, then switch to your regular grip and feel the difference. Repeat for 3 sets.",
    coachingCues: "Top hand strong. Control the barrel. Drive through it. Feel the whip.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 20,
    name: "Hook em Drill",
    slug: "drill",
    category: "standard",
    villain: "You’re missing your target. Your throws are wild and inaccurate.",
    tagline: "Improve your throwing accuracy and hit your target every time.",
    whatItIs: "This drill helps you get your body in line with your target. You'll focus on feeling your hips and shoulders rotate together, creating a powerful and accurate throw. It's all about connecting your body to where you want the ball to go.",
    whyWeDoit: "We do this drill to fix those wild throws. When your body isn't aligned, you lose power and accuracy. This drill teaches you to use your whole body to direct the ball, making you a more consistent and effective player.",
    howToRunIt: "Start by facing sideways to your target. As you begin your throwing motion, focus on rotating your hips first, then your shoulders. Keep your eyes locked on your target throughout the throw. Finish with your chest pointed at your target, like you're 'hooking' it in.",
    coachingCues: "Hips first. Stay connected. See your target. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 21,
    name: "The Knob to Knee Drill",
    slug: "drill",
    category: "standard",
    villain: "You're swinging with just your arms. Your lower body isn't helping you generate power.",
    tagline: "Feel your body connect for powerful swings.",
    whatItIs: "This drill teaches you to connect your lower body to your swing. You'll learn to use your legs and hips to create more power and consistency at the plate.",
    whyWeDoit: "We do this drill to fix weak swings and improve your power. When your body works as one, you hit the ball harder and more consistently. It's all about getting your whole body involved.",
    howToRunIt: "Start with your bat knob pointed at the ball. As you swing, focus on driving your back knee towards the pitcher. Keep your hands and hips working together. Finish your swing strong and balanced. Repeat for several reps, feeling the connection.",
    coachingCues: "Knob to the ball. Drive your knee. Stay connected. Explode through.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 22,
    name: "Ready at Release",
    slug: "drill",
    category: "standard",
    villain: "You're rushing your throw, losing power and accuracy. You're not finishing your motion.",
    tagline: "Feel strong, accurate, and powerful at your release point.",
    whatItIs: "This drill focuses on getting your body in the perfect position right before you release the ball. You'll pause at your release point, feeling everything aligned and strong. It's about building muscle memory for that powerful finish.",
    whyWeDoit: "Many players rush their throws, losing control and velocity. This drill teaches you to slow down, feel the correct mechanics, and ensure your body is ready to deliver maximum power and accuracy. It builds consistency in your throwing motion.",
    howToRunIt: "Start by getting into your throwing motion, but stop just before you release the ball. Hold this position for a few seconds, feeling your balance and arm slot. Make sure your front shoulder is closed and your hips are engaged. Then, complete your throw with a smooth, powerful finish. Repeat this several times, focusing on that perfect pause.",
    coachingCues: "Hold it. Feel strong. Finish through. Stay balanced.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 23,
    name: "Side-to-Side Water Bag Rip",
    slug: "drill",
    category: "standard",
    villain: "You get stuck. Your hips don't rotate. You lose power.",
    tagline: "Explode through the ball with powerful hip rotation.",
    whatItIs: "Grab a water bag and stand in your athletic stance. You'll rip the bag from one side of your body to the other, focusing on driving your hips. It's all about feeling that powerful rotation.",
    whyWeDoit: "This drill forces your hips to engage and rotate explosively, just like in your swing or throw. It builds rotational power, so you can hit harder and throw faster. You'll learn to use your whole body, not just your arms.",
    howToRunIt: "Hold the water bag with both hands. Start with the bag on one side of your body, near your hip. Explosively rip the bag across your body to the opposite side, driving your hips through the movement. Control the bag as it moves, then repeat to the other side. Do 3 sets of 8-10 reps per side.",
    coachingCues: "Rip it. Drive your hips. Stay athletic. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 24,
    name: "Water Bag Rotational Flow",
    slug: "drill",
    category: "standard",
    villain: "You're stiff and slow. Your rotation is weak, killing your power.",
    tagline: "Feel your core explode with power and fluidity.",
    whatItIs: "Grab that water bag and get ready to move. You're going to swing it around your body, focusing on smooth, powerful rotation. It's all about feeling that water shift and controlling it.",
    whyWeDoit: "This drill forces you to engage your core and hips, teaching you how to generate power from the ground up. It builds rotational strength and helps you connect your upper and lower body for a more explosive swing or throw.",
    howToRunIt: "Start with a light water bag. Stand tall, feet shoulder-width apart. Initiate the movement from your hips, swinging the bag around your body in a figure-eight motion. Keep your arms relaxed and let the water bag guide your rotation. Focus on a smooth, continuous flow, feeling the stretch and recoil in your core.",
    coachingCues: "Hips first. Feel the water. Stay loose. Explode through.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 25,
    name: "Water Bag Rotational Activation",
    slug: "drill",
    category: "standard",
    villain: "You're losing power in your swing. Your rotation is weak and disconnected.",
    tagline: "Unlock powerful rotation and feel your core ignite.",
    whatItIs: "This drill uses a water bag to activate your core and improve your rotational power. You'll feel the water shifting, forcing your body to stabilize and engage those deep rotational muscles. It's all about building a strong, explosive turn.",
    whyWeDoit: "We do this drill to help you generate more bat speed and throwing velocity. A strong, fluid rotation is key for powerful athletic movements. This drill teaches your body to work as one unit, transferring energy efficiently from your lower half through your core and into your swing or throw.",
    howToRunIt: "Grab a water bag and stand with your feet shoulder-width apart. Hold the bag with both hands and rotate your torso, swinging the bag from one side to the other. Focus on a smooth, powerful rotation, letting your hips and core lead the movement. Keep your arms extended but not locked. Repeat for desired reps on each side.",
    coachingCues: "Stay tall. Explode through. Finish strong. Feel the stretch.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 26,
    name: "Tall Shuffle and Rip",
    slug: "drill",
    category: "standard",
    villain: "You're losing power in your swing. You're off-balance and not driving through the ball.",
    tagline: "Feel powerful and stay balanced through your swing.",
    whatItIs: "This drill gets you moving with a waterbag to build strength and coordination. You'll shuffle tall, then explode into your rip.",
    whyWeDoit: "It teaches you to stay connected and generate power from the ground up. This means more bat speed and harder hits.",
    howToRunIt: "Start tall, holding the waterbag at your chest. Shuffle a few steps, keeping your chest up and eyes forward. Then, quickly \"rip\" the bag down and across your body, like you're throwing a punch. Stay balanced and finish strong.",
    coachingCues: "Stay tall. Shuffle smooth. Rip hard. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 27,
    name: "Dynamic Movement Rotational Swing",
    slug: "drill",
    category: "standard",
    villain: "Are you losing power in your swing? Is your body not connecting from the ground up?",
    tagline: "Feel your body connect and explode through the ball.",
    whatItIs: "Grab your waterbag and get ready to feel your core fire up. You'll be making a powerful, rotational swing motion, focusing on how your body moves as one unit. It's all about feeling that connection from your feet to your hands.",
    whyWeDoit: "This drill helps you build a strong, athletic swing. You'll learn to transfer energy efficiently from your lower body through your core and into your bat. This means more power and consistency when you hit.",
    howToRunIt: "Hold the waterbag with both hands. Start in your athletic stance, then initiate your swing by rotating your hips and core. Let the waterbag guide your movement, feeling the weight shift. Finish your swing powerfully, just like you're hitting a home run. Repeat for 10-12 reps per side.",
    coachingCues: "Ground up. Rotate hard. Feel the whip. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 28,
    name: "Waterbag Toss",
    slug: "drill",
    category: "standard",
    villain: "You're not using your whole body to throw. You're losing power and accuracy.",
    tagline: "Unlock your core power for explosive throws.",
    whatItIs: "Grab a waterbag and toss it like you're throwing a baseball. You'll feel your whole body working together. It's all about connecting your lower half to your upper half.",
    whyWeDoit: "This drill teaches you to use your core and hips to generate power. It helps you stop throwing with just your arm, which saves your arm and makes your throws stronger and more accurate.",
    howToRunIt: "Stand with your feet shoulder-width apart, holding the waterbag. Initiate the throw by rotating your hips and core, then follow through with your arms. Focus on a smooth, powerful motion. Repeat for 10-12 throws, then switch sides.",
    coachingCues: "Hips first. Feel the core. Explode through. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 29,
    name: "Happy Gilmore Waterbag Toss",
    slug: "drill",
    category: "standard",
    villain: "You're not using your body right. Stop just throwing with your arm.",
    tagline: "Feel your whole body explode into the throw.",
    whatItIs: "You're going to grab a waterbag and toss it like Happy Gilmore. It's all about getting that full body rotation and feeling the power from your legs and core. This isn't just an arm throw; it's a whole-body explosion.",
    whyWeDoit: "Too many players only use their arm, losing tons of power. This drill forces you to engage your lower half and core, teaching you how to generate real velocity. You'll learn to transfer energy efficiently, making your throws much stronger.",
    howToRunIt: "First, grab a waterbag that's heavy enough to challenge you. Stand with your back to the target, just like Happy Gilmore. Take a few steps, building momentum, and then unleash the throw using your entire body. Focus on rotating your hips and shoulders, letting the waterbag fly. Repeat this for a few sets, really feeling that full-body connection.",
    coachingCues: "Rotate your hips. Explode through your core. Finish strong. Feel the power.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 30,
    name: "The Nine Pocket Drill",
    slug: "drill",
    category: "standard",
    villain: "You're missing your spots. Your pitches aren't hitting the catcher's glove where you want them.",
    tagline: "Hit your spots, every single time.",
    whatItIs: "This drill uses a waterbag to help you visualize and hit nine specific targets in the strike zone. You'll focus on precision, making sure every pitch goes exactly where you intend it to. It's all about control and consistency.",
    whyWeDoit: "We do this drill to sharpen your command on the mound. When you can consistently hit your spots, you'll get more swings and misses, weak contact, and keep hitters off balance. It builds the muscle memory you need for game-day success.",
    howToRunIt: "Set up a waterbag or a target with nine distinct sections. From the mound, throw pitches aiming for each of the nine pockets. Focus on hitting each one precisely before moving to the next. Repeat until you feel confident in your accuracy.",
    coachingCues: "Hit your spot. Find the pocket. Trust your arm. Finish strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 31,
    name: "Lasso Drill",
    slug: "drill",
    category: "standard",
    villain: "You're rushing your swing. You're not letting your body work together.",
    tagline: "Feel your body connect, find your rhythm, and unleash power.",
    whatItIs: "Grab a waterbag or a light bat. You're going to make big, fluid circles with it, like you're lassoing something. Focus on feeling your core and hips lead the movement, letting your arms follow naturally.",
    whyWeDoit: "This drill teaches you to connect your lower body to your upper body. It helps you stop muscling the ball and start using your whole body for power, creating a smooth, powerful swing.",
    howToRunIt: "Stand tall, feet shoulder-width apart. Start swinging the waterbag in a big circle, feeling your hips initiate the movement. Keep your arms relaxed and let the bag's momentum guide you. Do 10-15 swings per side, focusing on a continuous, flowing motion.",
    coachingCues: "Hips first. Feel the whip. Stay loose. Let it flow.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
  {
    id: 32,
    name: "Fogel Water Bag Drill",
    slug: "drill",
    category: "standard",
    villain: "Jerky movements and poor balance. You lose control when things get unstable.",
    tagline: "Feel your core, control the chaos, and move with power.",
    whatItIs: "You're going to use a water bag, which is super unstable. It forces your body to work harder to stay balanced. This drill makes you strong and smooth.",
    whyWeDoit: "This drill challenges your stability in a unique way. It teaches your body to adapt to unpredictable forces. You'll build a rock-solid core and better body control.",
    howToRunIt: "Fill a bag with water, but not all the way. Hold it and perform your baseball movements slowly. Focus on keeping the water from sloshing around too much. Start light, then add more water as you get better. Do this for a few sets, really feeling your body stabilize.",
    coachingCues: "Stay smooth. Control the water. Feel your core. Be strong.",
    videoUrl: "",
    thumbnailUrl: yt(""),
  },
];

export const standardDrills = drills.filter(d => d.category === "standard");
export const waterbagDrills = drills.filter(d => d.category === "waterbag");
